import os
import sys
import rtconfig

if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + '/../..')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
try:
    from building import *
except:
    print('Cannot found RT-Thread root directory, please check RTT_ROOT')
    print(RTT_ROOT)
    exit(-1)
 
TARGET = 'rtthread.' + rtconfig.TARGET_EXT

DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
	AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
	CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
	AR = rtconfig.AR, ARFLAGS = '-rc',
	LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
env['ASCOM'] = env['ASPPCOM']

Export('RTT_ROOT')
Export('rtconfig')

SDK_ROOT = os.path.abspath('./')

if os.path.exists(SDK_ROOT + '/ae350_soc'):
    libraries_path_prefix = SDK_ROOT + '/ae350_soc'
else:
    libraries_path_prefix = os.path.dirname(SDK_ROOT) + '/ae350_soc'

SDK_LIB = libraries_path_prefix
Export('SDK_LIB')

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT)

# include libraries
objs.extend(SConscript(os.path.join(libraries_path_prefix, 'ae350', 'SConscript'), variant_dir='build/libraries/ae350', duplicate=0))

# include configuration
objs.extend(SConscript(os.path.join(libraries_path_prefix, 'config', 'SConscript'), variant_dir='build/libraries/config', duplicate=0))

# include drivers
objs.extend(SConscript(os.path.join(libraries_path_prefix, 'driver', 'SConscript'), variant_dir='build/libraries/driver', duplicate=0))

# include drivers
objs.extend(SConscript(os.path.join(libraries_path_prefix, 'lib', 'SConscript'), variant_dir='build/libraries/lib', duplicate=0))

# include drivers
objs.extend(SConscript(os.path.join(libraries_path_prefix, 'sag', 'SConscript'), variant_dir='build/libraries/sag', duplicate=0))

# make a building
DoBuilding(TARGET, objs)
