import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
cwd = GetCurrentDir()

src = Split('''
ae350.c
initfini.c
loader.c
reset.c
''')

path = [cwd]

group = DefineGroup('ae350', src, depend = [''], CPPPATH = path)

Return('group')
