import rtconfig
from building import *

cwd = GetCurrentDir()

# add the general drvers.
# src = Glob("*.c")
src = Split('''
gpio.c
spi.c
uart.c
''')

CPPPATH = [cwd]

group = DefineGroup('lib', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
